static-root: /file
database-name: flina
database-user: root
database-pass: rootroot

server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/${database-name}?serverTimezone=CST&useUnicode=true&characterEncoding=UTF-8
    username: ${database-user}
    password: ${database-pass}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 10
      min-idle: 10
      max-idle: 20
      max-wait-millis: 500
      time-between-eviction-runs-millis: 20000
      remove-abandoned-timeout: 20000
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
